openapi: 3.1.0
info: { title: Keijiban API, version: 0.1.0 }
servers: [{ url: http://localhost/api }]
paths:
  /auth/register: { post: { summary: Register, responses: { '201': { description: created }, '422': { description: validation } } } }
  /auth/login: { post: { summary: Login (sets cookie), responses: { '204': { description: ok }, '401': { description: unauthorized } } } }
  /auth/logout: { post: { summary: Logout, responses: { '204': { description: ok } } } }
  /user: { get: { summary: Current user, responses: { '200': { description: ok } } } }
  /threads:
    get: { summary: List threads, responses: { '200': { description: ok } } }
    post: { summary: Create thread, responses: { '201': { description: created } } }
  /threads/{id}:
    get: { summary: Get thread, responses: { '200': { description: ok }, '404': { description: not found } } }
    patch: { summary: Update (owner only), responses: { '200': { description: ok }, '403': { description: forbidden } } }
    delete: { summary: Delete (owner only), responses: { '204': { description: ok } } }
  /threads/{id}/posts:
    get: { summary: List posts, responses: { '200': { description: ok } } }
    post: { summary: Create post, responses: { '201': { description: created } } }
